name: Build and deploy the website
on:
  push:
    branches:
      - site-source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build the website
        run: |
          yarn
          yarn build

      - name: Add .nojekkyll
        run: touch ./public/.nojekyll

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v2.3.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
